server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/db_userservice
    username: webservice
    password: P@ssw0rd

  security:
    user:
      name: john
password: P@ssw0rd