service: my-service
app: myapp-dev
tenant: nostprumprajee
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

functions:
  bnk:
    handler: handler.bnk
    events:
      - http:
         path: bnk/members
method: get