version: '3.1'

services:
  web:
    restart: always
    image: go-mysql-crud
    ports:
      - 8005:8005
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=go-mysql-crud"
      - "DB_PASS=12345"
  
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /mysql:/var/lib/mysql
    
